name: tp_proto
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  grpc: ^3.0.2
  protobuf: ^2.0.1
dev_dependencies: {build_runner: ^2.1.11, protoc_builder: ^0.2.1+1}
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - tp.proto